300: "訂單處理中(已收到訂單資料)"
310: "上傳電子訂單檔處理中"
311: "上傳退貨電子訂單處理中"
325: "準備退貨"
2000: "出貨訂單修改"
2001: "檔案傳送成功"
2002: "出貨單號不合規則"
2003: "XML 檔內出貨單號重複"
2004: "出貨單號重複上傳使用(驗收時發現)"
2005: "日期格式不符"
2006: "訂單金額或代收金額錯誤"
2007: "商品類型為空"
2008: "訂單為空"
2009: "門市店號為空"
2010: "出貨日期為空"
2011: "出貨金額為空"
2012: "出貨編號不存在"
2013: "母廠商不存在"
2014: "子廠商不存在"
2015: "出貨編號已存在(單筆)"
2016: "門市已關轉店，將進行退貨處理"
2017: "出貨日期不符合規定"
2018: "服務類型不符規定(如只開取貨付款服務，確使用純取貨服務)"
2019: "商品類型不符規定"
2020: "廠商尚未申請店配服務"
2021: "同一批次出貨編號重覆(批次)"
2022: "出貨金額不符規定"
2023: "取貨人姓名為空"
2024: "物流作業驗收中"
2025: "門市轉店號(舊門市店號已更新)"
2026: "無此門市，將進行退貨處理"
2027: "門市指定時間不配送(六、日)"
2028: "門市關轉店，3 日內未更新 SUP(新店號)便至退貨流程"
2029: "門市尚未開店"
2030: "物流中心驗收成功"
2031: "未到貨(物流端未收到該商品)"
2032: "商品瑕疵(進物流中心)"
2033: "超材"
2034: "違禁品(退貨及罰款處理)"
2035: "訂單資料重覆上傳"
2036: "已過門市進貨日(未於指定時間內寄至物流中心)"
2037: "門市關轉(可使用 SUP 檔案更新原單號更新門市與出貨日)"
2038: "第一段標籤規格錯誤"
2039: "第一段標籤無法判讀"
2040: "第一段標籤資料錯誤"
2041: "物流中心理貨中"
2042: "商品遺失"
2043: "門市指定不配送(六、日)"
2045: "不正常到貨(商品提早到物流中心)"
2046: "廠商未至門市取退貨，商品已退回至大智通"
2047: "正常二退(退貨時間延長，在判賠期限內退回)"
2048: "商品瑕疵(商品在物流中心)"
2049: "門市關店，將進行退貨處理"
2050: "門市轉店，將進行退貨處理"
2051: "廠商要求提早退貨（廠商出錯商品）"
2052: "違禁品(退貨及罰款處理)"
2053: "刷 A 給 B"
2054: "消費者要求提早拉退（消費者下訂單後又跟廠商取消）"
2055: "更換門市"
2057: "車輛故障，後續配送中"
2058: "天候不佳，後續配送中"
2059: "道路中斷，後續配送中"
2060: "門市停業中，將進行退貨處理"
2061: "缺件(商品未至門市)"
2062: "門市報缺"
2063: "門市配達"
2065: "EC 收退"
2066: "異常收退(商品破損、外袋破損、消費者取錯件、誤刷代收等，提早從門市退貨)"
2067: "消費者成功取件"
2068: "交貨便收件(A 門市收到件寄件商品)"
2069: "退貨便收件(商品退回指定 C 門市)"
2070: "退回原寄件門市且已取件"
2071: "門市代碼格式錯誤"
2094: "包裹異常不配送"
2101: "門市關轉店"
2102: "門市舊店號更新"
2103: "無取件門市資料"
2104: "門市臨時關轉店"
3001: "轉運中(即集貨)"
3002: "不在家"
3003: "配完"
3004: "送錯 BASE (送錯營業所)"
3005: "送錯 CENTER(送錯轉運中心)"
3006: "配送中"
3007: "公司行號休息"
3008: "地址不明，聯繫寄件人確認"
3009: "搬家"
3010: "轉寄(如原本寄到 A，改寄 B)"
3011: "暫置營業所(收件人要求至營業所取貨)"
3012: "到所(收件人要求到站所取件)"
3013: "當配下車(當日配送 A 至 B 營業所，已抵達 B 營業所)"
3014: "當配上車(當日配送從 A 至 B 營業所，已抵達 A 營業所)"
3015: "空運配送中"
3016: "配完狀態刪除"
3017: "退回狀態刪除(代收退貨刪除)"
3018: "到店尚未取貨，簡訊通知取件"
3019: "退件到店尚未取貨，簡訊通知取件"
3020: "貨件未取退回物流中心"
3021: "退貨商品未取退回物流中心"
3022: "買家已到店取貨"
3023: "賣家已取買家未取貨"
3024: "貨件已至物流中心"
3025: "退貨已退回物流中心"
3029: "商品已轉換店（商品送達指定更換之取件店舖）"
3031: "退貨商品已轉換店（退貨商品送達指定更換之取件店舖）"
3032: "賣家已到門市寄件"
4001: "退貨商品已至門市交寄"
4002: "退貨商品已至物流中心"
5001: "損壞，站所將協助退貨"
5002: "遺失"
5003: "BASE 列管"
5004: "一般單退回"
5005: "代收退貨"
5006: "代收毀損"
5007: "代收遺失"
5008: "退貨配完"
5009: "進貨門市發生緊急閉店，提早退貨至物流中心"
7001: "超大(通常發生於司機取件，不取件)"
7002: "超重(通常發生於司機取件，不取件)"
7003: "地址錯誤，聯繫收件人"
7004: "航班延誤"
7005: "託運單刪除"
7006: "小物流遺失"
7007: "門市遺失"
7008: "小物流破損，退回物流中心"
7009: "商品包裝不良（物流中心反應）"
7010: "商品包裝不良（門市反應）"
7011: "取件門市閉店，轉退回原寄件店"
7012: "條碼重複或錯誤，物流中心客服處理"
7013: "訂單超過驗收期限（商家未出貨）"
7014: "商家未到貨（若訂單成立隔日未到貨即會發送，直到訂單失效刪除）"
9001: "退貨已取"
9002: "退貨已取"
9999: "訂單取消"
2072: "商品配達賣家取退貨門市"
2073: "商品配達買家取貨門市"
2074: "消費者七天未取，商品離開買家取貨門市"
2075: "廠商未至門市取退貨，商品退回至大智通"